Repository IvanIhnatsiuk/react-native-advanced-input-mask, pull requests merged in 2024-12, with the labels that each got.

#26 fix: android build error
  android/src/oldarch/java/com/maskedtextinput/AdvancedTextInputMaskDecoratorViewManagerSpec.kt
Labels: bug

#27 chore: release: release 1.1.3
  example/ios/Podfile.lock
  package.json
Labels: release

#28 fix: update readme file
  README.md
Labels: documentation

#5 feat: add NotificationCenter compatibility
  ios/AdvancedTextInputMaskDecoratorView.swift
  ios/NotifyingAdvancedTexInputMaskListener.swift
Labels: enhancement
