Repository IvanIhnatsiuk/react-native-advanced-input-mask, pull requests merged in 2025-01, with the labels that each got.

#32 feat: add web example app
  WebExample/.gitignore
  WebExample/README.md
  WebExample/app.json
  WebExample/assets/favicon.png
  WebExample/babel.config.js
  WebExample/index.js
  WebExample/metro.config.js
  WebExample/package.json
  WebExample/src/App.tsx
  WebExample/tsconfig.json
  package.json
  yarn.lock
Labels: enhancement

#33 🌐 Web support 🌐
  WebExample/package.json
  WebExample/src/App.tsx
  WebExample/tsconfig.json
  example/Gemfile.lock
  example/android/gradle.properties
  example/ios/Podfile.lock
  example/package.json
  package.json
  src/index.tsx
  src/index.web.tsx
  src/native/MaskedTextInputNative.tsx
  src/native/specs/AdvancedTextInputMaskDecoratorViewNativeComponent.ts
  src/native/views/MaskedTextInput/index.tsx
  src/types.ts
  src/web/AdvancedTextInputMaskListener.ts
  src/web/helper/CaretStringIterator.ts
  src/web/helper/Compiler.ts
  src/web/helper/FormatError.ts
  src/web/helper/FormatSanitizer.ts
  src/web/helper/Mask.ts
  src/web/helper/RTLCaretStringIterator.ts
  src/web/helper/RTLMask.ts
  src/web/helper/affinityCalculationStrategy.ts
  src/web/hooks/useMaskedTextInputListener/index.ts
  src/web/hooks/useMaskedTextInputListener/types.ts
  src/web/model/CaretString.ts
  src/web/model/constants.ts
  src/web/model/state/EOLState.ts
  src/web/model/state/FixedState.ts
  src/web/model/state/FreeState.ts
  src/web/model/state/OptionalValueState.ts
  src/web/model/state/State.ts
  src/web/model/state/ValueState.ts
  src/web/model/types.ts
  src/web/model/utils.ts
  src/web/views/MaskedTextInput/index.tsx
  tsconfig.json
  yarn.lock
Labels: enhancement

#37 chore: react native 0.77
  WebExample/package.json
  android/src/main/java/com/maskedtextinput/managers/AdvancedTextInputMaskDecoratorViewManager.kt
  example/Gemfile
  example/Gemfile.lock
  example/android/build.gradle
  example/ios/File.swift
  example/ios/MaskedTextInputExample-Bridging-Header.h
  example/ios/MaskedTextInputExample.xcodeproj/project.pbxproj
  example/ios/MaskedTextInputExample/AppDelegate.h
  example/ios/MaskedTextInputExample/AppDelegate.mm
  example/ios/MaskedTextInputExample/AppDelegate.swift
  example/ios/MaskedTextInputExample/main.m
  example/ios/MaskedTextInputExampleTests/Info.plist
  example/ios/MaskedTextInputExampleTests/MaskedTextInputExampleTests.m
  example/ios/Podfile
  example/ios/Podfile.lock
  example/package.json
  package.json
  src/native/specs/AdvancedTextInputMaskDecoratorViewNativeComponent.ts
  yarn.lock
Labels: enhancement

#36 feat: allowed keys
  README.md
  android/src/main/java/com/maskedtextinput/listeners/ReactMaskedTextChangeListener.kt
  android/src/main/java/com/maskedtextinput/managers/AdvancedTextInputMaskDecoratorViewManager.kt
  android/src/main/java/com/maskedtextinput/views/AdvancedTextInputMaskDecoratorView.kt
  android/src/oldarch/java/com/maskedtextinput/AdvancedTextInputMaskDecoratorViewManagerSpec.kt
  ios/AdvancedTextInputMaskDecoratorView.swift
  ios/AdvancedTextInputViewContainer.h
  ios/AdvancedtextInputMaskDecoratorView.mm
  ios/MaskedTextInputManager.mm
  ios/NotifyingAdvancedTexInputMaskListener.swift
  src/native/specs/AdvancedTextInputMaskDecoratorViewNativeComponent.ts
  src/native/views/MaskedTextInput/index.tsx
  src/types.ts
  src/web/AdvancedTextInputMaskListener.ts
  src/web/hooks/useMaskedTextInputListener/index.ts
  src/web/views/MaskedTextInput/index.tsx
Labels: enhancement

#42 feat: add default value formatting on web
  WebExample/src/App.tsx
  src/web/AdvancedTextInputMaskListener.ts
  src/web/hooks/useMaskedTextInputListener/index.ts
  src/web/views/MaskedTextInput/index.tsx
Labels: enhancement

#43 chore: release v1.2.1
  example/ios/Podfile.lock
  package.json
Labels: library version changed

#45 fix: advanced text input view is not cleaned up during recycling
  .gitignore
  android/src/main/java/com/maskedtextinput/views/AdvancedTextInputMaskDecoratorView.kt
  example/android/app/src/main/java/com/maskedtextinputexample/MainActivity.kt
  example/ios/Podfile.lock
  example/package.json
  example/src/App.tsx
  example/src/navigation/Root/index.tsx
  example/src/navigation/Root/types.ts
  example/src/navigation/index.tsx
  example/src/navigation/screenNames.ts
  example/src/screens/Main/index.tsx
  example/src/screens/Main/styles.ts
  example/src/screens/RNTextInput/index.tsx
  example/src/screens/RNTextInput/styles.ts
  ios/AdvancedTextInputMaskDecoratorView.swift
  ios/AdvancedTextInputViewContainer.h
  ios/AdvancedtextInputMaskDecoratorView.mm
  yarn.lock
Labels: bug

#50 feat: add package size job on CI
  .github/workflows/size-diff-calculation.yml
Labels: CI

#52 fix: default value is not set during re-renders/unmount
  example/src/navigation/Root/index.tsx
  example/src/navigation/screenNames.ts
  example/src/screens/Date/index.tsx
  example/src/screens/Date/styles.ts
  example/src/screens/Main/index.tsx
  ios/AdvancedTextInputMaskDecoratorView.swift
  ios/AdvancedtextInputMaskDecoratorView.mm
Labels: bug
